import React,{useState} from 'react';
import {CheckCircle2,Eye,EyeOff,KeyRound,LoaderCircle,LockKeyhole,Mail,ShieldCheck,UserRound} from 'lucide-react';
import type {User} from '../types';
import {authApi} from '../lib/supabase';

export function AccountPage({currentUser}:{currentUser:User}){
 const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSuccess('');if(password.length<8)return setError('كلمة المرور يجب أن تكون 8 أحرف على الأقل.');if(!/[A-Za-z]/.test(password)||!/[0-9]/.test(password))return setError('استخدم حرفاً ورقماً واحداً على الأقل.');if(password!==confirm)return setError('كلمتا المرور غير متطابقتين.');setBusy(true);try{await authApi.updatePassword(password);setPassword('');setConfirm('');setSuccess('تم تحديث كلمة المرور بنجاح.');}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث كلمة المرور');}finally{setBusy(false)}};
 return <div className="space-y-6 max-w-3xl mx-auto"><section className="bg-slate-900 text-white rounded-2xl p-6 sm:p-8 border border-slate-800 relative overflow-hidden"><div className="absolute w-48 h-48 bg-blue-600/15 rounded-full blur-3xl -left-10 -top-10"/><div className="relative flex items-center gap-4"><img src={currentUser.avatar} alt="" className="w-16 h-16 rounded-2xl ring-2 ring-blue-500/40"/><div><p className="text-xs font-black text-blue-400 mb-1">إعدادات الحساب</p><h2 className="text-2xl font-black">حسابي</h2><p className="text-xs text-slate-400 mt-1">بيانات الدخول والأمان</p></div></div></section>
 <section className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 sm:p-7"><h3 className="font-black flex items-center gap-2 mb-5"><UserRound className="w-5 h-5 text-blue-600"/> بيانات الحساب</h3><div className="grid sm:grid-cols-2 gap-4"><div className="bg-slate-50 rounded-xl border border-slate-200 p-4"><span className="text-[10px] font-black text-slate-400 block mb-1">الاسم</span><b className="text-sm">{currentUser.name}</b></div><div className="bg-slate-50 rounded-xl border border-slate-200 p-4"><span className="text-[10px] font-black text-slate-400 flex items-center gap-1 mb-1"><Mail className="w-3 h-3"/> البريد الإلكتروني — غير قابل للتعديل</span><b dir="ltr" className="text-sm block text-right truncate">{currentUser.email}</b></div></div></section>
 <form onSubmit={submit} className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 sm:p-7"><div className="flex items-start gap-3 mb-6"><span className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 grid place-items-center"><KeyRound className="w-5 h-5"/></span><div><h3 className="font-black">تغيير كلمة المرور</h3><p className="text-xs text-slate-400 mt-1">استخدم كلمة قوية لا تقل عن 8 أحرف.</p></div></div>{error&&<p className="bg-rose-50 border border-rose-200 text-rose-700 text-xs font-bold p-3 rounded-xl mb-4">{error}</p>}{success&&<p className="bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-bold p-3 rounded-xl mb-4 flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>{success}</p>}<div className="grid sm:grid-cols-2 gap-4"><label><span className="text-xs font-black block mb-1.5">كلمة المرور الجديدة</span><div className="relative"><LockKeyhole className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input required minLength={8} type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="w-full bg-slate-50 border border-slate-200 rounded-xl py-3 pr-10 pl-10 outline-none focus:ring-2 focus:ring-blue-500"/><button type="button" onClick={()=>setShow(!show)} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">{show?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div></label><label><span className="text-xs font-black block mb-1.5">تأكيد كلمة المرور</span><div className="relative"><ShieldCheck className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input required minLength={8} type={show?'text':'password'} value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full bg-slate-50 border border-slate-200 rounded-xl py-3 pr-10 pl-3 outline-none focus:ring-2 focus:ring-blue-500"/></div></label></div><button disabled={busy} className="mt-5 w-full sm:w-auto bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl text-sm font-black flex items-center justify-center gap-2">{busy?<LoaderCircle className="w-4 h-4 animate-spin"/>:<KeyRound className="w-4 h-4"/>} حفظ كلمة المرور الجديدة</button></form></div>;
}
